"""Схема из миграций не должна расходиться с моделями.

Расхождение стоит дорого и обнаруживается поздно: контейнер поднимет
схему по миграциям, а код будет ждать другую. Тест синхронный —
``migrations/env.py`` сам крутит ``asyncio.run``, поэтому запускать его
внутри уже работающего цикла нельзя.
"""

from __future__ import annotations

import pytest
from alembic import command
from alembic.util.exc import AutogenerateDiffsDetected

from tests.conftest import alembic_config


def test_migrations_match_models(migrated_database: None) -> None:
    try:
        command.check(alembic_config())
    except AutogenerateDiffsDetected as exc:
        pytest.fail(f"Миграции разошлись с моделями: {exc}")
